### ISSUE TITLE
Add balloon folder bookmark (favourites) on Mac OS X

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-desktop#31]
#### Description
**Is**:
There is no balloon folder in the favourites category within finder.

**Should**:
A balloon folder short cut under favourites.

#### balloon desktop version
0.0.32

#### Your client operating system
Mac OS X 10.13.2

**Comment by pixtron** [comment]
Eventually [mysides](https://github.com/mosen/mysides) could be used.

NOTE: the hint that since OSX 10.11 slftool could be used to achieve similar things, is not anymore valid, as the `add-item` functionality has been removed with OSX 10.13 
https://apple.stackexchange.com/questions/305034/sfltool-add-item-to-add-finder-favorite-stopped-working-on-high-sierra

**Comment by raffis** [comment]
Fixed by https://github.com/gyselroth/node-advanced-desktop
